tasks:
  - source: scripts/get.py
    product:
      nb: products/get.html
      data: products/raw.csv

  - source: scripts/clean.py
    product:
      nb: products/clean.html
      data: products/clean.csv
