# this is tne base environment, specific projects might have special
# dependencies. Since binder builds the image based on a single environment
# we provide this one which includes dependencies most projects need anyway)
name: ploomber_projects

channels:
  - conda-forge

dependencies:
  - python=3.7
  - tree
  - numpy
  - pandas
  - pip
  - pygraphviz
  - matplotlib
  - r-base
  - r-irkernel
  - pip:
    - seaborn
    - ploomber
    - jupyter_client>=5.3.1

