meta:
  extract_product: False

  source_loader:
    module: ml_online

  import_tasks_from: pipeline-features.yaml


serializer: ml_online.io.serialize
unserializer: ml_online.io.unserialize

tasks:
  - source: ml_online.tasks.raw.get
    product: "{{cwd}}/products/raw/get.parquet"
    params:
      sample: '{{sample}}'
  
  - source: notebooks/fit.py
    product:
      nb: "{{cwd}}/products/report.html"
      model: "{{cwd}}/products/model.pickle"
