name: ml-intermediate

channels:
  - conda-forge

dependencies:
  - python=3.9
  - pip
  - pygraphviz

  - pip:
    - ploomber==0.13.6
    - soopervisor
    - pandas
    - scikit-learn
    - pyarrow
    - sklearn-evaluation
    - ipywidgets