clients:
  File: clients.storage
  SQLDump: clients.db
  SQLScript: clients.db

tasks:
  - source: transform.sql
    product: [my_dataset, some_table, table]

  - source: script.sql
    product: products/dump.parquet
    chunksize: null
