name: spec-api-directory

dependencies:
  - python=3.7
  - pip
  - pip:
    - git+https://github.com/ploomber/ploomber@dev
    - numpy
    - pandas
    - matplotlib
    - scikit-learn
    - seaborn
    - pyarrow
