tasks:
    # tasks.get, features and join are python functions
  - source: tasks.get
    product: output/get.parquet

  - source: tasks.features
    product: output/features.parquet

  - source: tasks.join
    product: output/join.parquet

    # fit.py is a script
  - source: fit.py
    name: fit
    product:
        # this output notebook is the model's evaluation report
        nb: output/nb.ipynb
        model: output/model.pickle
