name: ml-basic

channels:
  - conda-forge

dependencies:
  - python=3.7
  - pip

  - pip:
    - git+https://github.com/ploomber/ploomber@dev
    - pandas
    - scikit-learn
    - pyarrow
    - sklearn-evaluation
    - jupyter
    # - google-cloud-storage