meta:
  extract_upstream: True
  extract_product: False
  jupyter_hot_reload: True
  jupyter_functions_as_notebooks: True

# enable client if you want to upload arfifacts to google cloud storage
# NOTE: you must provide your own credentials
# clients:
  # File: clients.get_storage_client

tasks:
    # tasks.get, features and join are python functions
  - source: tasks.get
    product: output/get.parquet

  - source: tasks.features
    product: output/features.parquet

  - source: tasks.join
    product: output/join.parquet

    # fit.py is a script executed as a notebook
  - source: fit.py
    name: fit
    product:
        nb: output/nb.ipynb
        model: output/model.pickle
