tasks:
   # source is the code you want to execute (.ipynb also supported)
  - source: 1-get.py
    # products are task's outputs
    product:
      # scripts generate executed notebooks as outputs
      nb: output/1-get.ipynb
      # you can define as many outputs as you want
      data: output/data.csv
    
  - source: 2-clean.py
    product:
      nb: output/2-clean.ipynb
      data: output/clean.csv

  - source: 3-plot.py
    product:
      nb: output/3-plot.ipynb
