name: spec

dependencies:
  - python=3.7
  - numpy
  - pandas
  - pip
  - matplotlib
  - pygraphviz
  - sqlalchemy
  - pip:
    - faker
    - seaborn
    - git+https://github.com/ploomber/ploomber.git#egg=ploomber[all]

