- class: NotebookRunner
  source: load.py
  product:
    nb: output/load.ipynb
    data: output/data.csv

- class: NotebookRunner
  name: clean
  source: clean.py
  product:
    nb: output/clean.ipynb
    data: output/clean.csv
  upstream: [load.py]

- class: NotebookRunner
  name: plot
  source: plot.py
  product: output/plot.ipynb
  upstream: clean
