meta:
  extract_product: False

  product_default_class:
    SQLScript: SQLiteRelation

config:
  hot_reload: True

clients:
  # tasks
  SQLScript: config.get_client
  SQLDump: config.get_client
  # products
  SQLiteRelation: config.get_client

tasks:
  - source: filter_sales.sql
    product: [filtered_sales, table]

  - source: group_sales.sql
    product: [grouped_sales, table]

  - source: filter_prices.sql
    product: [filtered_prices, table]

  - source: join.sql
    product: [joined, table]

  - class: SQLDump
    source: join_dump.sql
    product: output/joined_data.csv
    chunksize: null

  - source: plot.py
    product: output/plot.html