name: ml-intermediate

channels:
  - conda-forge

dependencies:
  - python=3.9
  - pip

  - pip:
    - ploomber
    - soopervisor
    - pandas
    - scikit-learn
    - pyarrow
    - sklearn-evaluation