name: ml-intermediate

channels:
  - conda-forge

dependencies:
  - python=3.8

  - pip:
    - git+https://github.com/ploomber/ploomber@dev
    - pandas
    - scikit-learn
    - pyarrow
    - sklearn-evaluation