meta:
  extract_upstream: True
  extract_product: False
  jupyter_functions_as_notebooks: True
  import_tasks_from: pipeline-features.yaml

tasks:
  - source: tasks.get.fn
    name: get
    # all products are parametrized (default values are loaded from env.yaml),
    # and can be overriden using the command line interface
    product: "output/{{ 'sample' if sample else 'full' }}/get.parquet"
    params:
      # we can also pass parameters to tasks
      sample: '{{sample}}'

  - source: fit.py
    name: fit
    product:
        # changing the extension triggers a format conversion automatically
        nb: "output/{{ 'sample' if sample else 'full' }}/nb.html"
        model: "output/{{ 'sample' if sample else 'full' }}/model.pickle"
    # use this parameter to customize the output notebook (optional)
    nbconvert_export_kwargs:
      # do not show input code
      exclude_input: True
      # selectively remove cells based on tags
      config:
        TagRemovePreprocessor: {'remove_cell_tags': ['model-training']}
        HTMLExporter: {'preprocessors': ['nbconvert.preprocessors.TagRemovePreprocessor']}
    # for details, check out nbconvert's docs:
    # https://nbconvert.readthedocs.io/en/latest/config_options.html#preprocessor-options