name: ci
on: push

jobs:
  # missing: debugging
  # missing: sql-templating
    
  projects:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        folder:
          - ml-basic
          - ml-intermediate
          - etl
          - parametrized
          - python-api
          - spec-api-python
          - spec-api-r
    env:
      FOLDER: ${{ matrix.folder }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - run: |
          # run pipeline
          pip install soopervisor
          cd $FOLDER
          soopervisor build --clean-products-path

          # test readme works
          eval "$(conda shell.bash hook)"
          exec bash
          conda activate $FOLDER
          pip install invoke
          invoke pre-deploy --name $FOLDER


  spec-api-directory:
    runs-on: ubuntu-latest
    name: spec-api-directory
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - run: |
          eval "$(conda shell.bash hook)"
          exec bash
          cd spec-api-directory/
          conda env create --file environment.yml --name env
          conda activate env
          ploomber build --entry-point .

  spec-api-sql:
    runs-on: ubuntu-latest
    name: spec-api-sql
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - run: cd spec-api-sql/setup/ && bash setup.sh && cd ../..
      - run: pip install soopervisor
      - run: cd spec-api-sql/ && soopervisor build --clean-products-path

  testing:
    runs-on: ubuntu-latest
    name: testing
    steps:
      # this step makes your repo available to the next one
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - run: |
          pip install pandas soopervisor
          cd testing
          mkdir output
          cd setup && python script.py && cd ..
          soopervisor build --clean-products-path
  
  ml-advanced:
    runs-on: ubuntu-latest
    name: ml-advanced
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - run: |
          cd ml-advanced
          pip install "."
          pytest
