name: ci
on: push

jobs:
  spec:
    runs-on: ubuntu-latest
    name: spec ci
    steps:
      # this step makes your repo available to the next one
      - uses: actions/checkout@v2
      - run: cd spec/setup/ && bash setup.sh && cd ../..
      # our action will move to "path", configure the environment and then build
      # the pipeline.yaml spec
      - uses: ploomber/ci@master
        with:
          path: spec/

  basic-tutorial:
    runs-on: ubuntu-latest
    name: basic-tutorial ci
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - run: pip install git+https://github.com/ploomber/ci-for-ds@dev-edu && cd basic-tutorial/ && ploomberci --clean-product-root

  spec-r:
    runs-on: ubuntu-latest
    name: spec-r
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - run: pip install git+https://github.com/ploomber/ci-for-ds@dev-edu && cd spec-r/ && ploomberci --clean-product-root
  
  co2-emissions:
    runs-on: ubuntu-latest
    name: co2-emissions
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - run: pip install git+https://github.com/ploomber/ci-for-ds@dev-edu && cd contrib/co2-emissions && ploomberci --clean-product-root