name: ci
on: push

jobs:
  spec:
    runs-on: ubuntu-latest
    name: spec-api-sql
    steps:
      # this step makes your repo available to the next one
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - run: cd spec-api-sql/setup/ && bash setup.sh && cd ../..
      - run: pip install soopervisor
      - run: cd spec-api-sql/ && soopervisor build --clean-products-path

  python-api:
    runs-on: ubuntu-latest
    name: python-api ci
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - run: pip install soopervisor
      - run: cd python-api/ && soopervisor build --clean-products-path

  spec-api-r:
    runs-on: ubuntu-latest
    name: spec-api-r
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - run: pip install soopervisor
      - run: cd spec-api-r/ && soopervisor build --clean-products-path

  etl:
    runs-on: ubuntu-latest
    name: etl
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - run: pip install soopervisor
      - run: cd etl/ && soopervisor build --clean-products-path

  basic-ml:
    runs-on: ubuntu-latest
    name: basic-ml
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - run: |
          cd basic-ml
          pip install "."
          pip install -r requirements.txt
          pytest
          cd spec
          mkdir output
          ploomber build
