name: ci
on: push

jobs:
  spec:
    runs-on: ubuntu-latest
    name: spec ci
    steps:
      # this step makes your repo available to the next one
      - uses: actions/checkout@v2
      - run: cd spec/setup/ && bash setup.sh && cd ../..
      # our action will move to "path", configure the environment and then build
      # the pipeline.yaml spec
      - uses: ploomber/ci@master
        with:
          path: spec/

  basic-tutorial:
    runs-on: ubuntu-latest
    name: basic-tutorial ci
    steps:
      - uses: actions/checkout@v2
      - uses: ploomber/ci@master
        with:
          path: basic-tutorial/

  spec-r:
    runs-on: ubuntu-latest
    name: spec-r
    steps:
      - uses: actions/checkout@v2
      - run:
        - conda env create --file environment.yml
        - conda activate ploomber_projects
        - cd spec-r/
        - ploomber build
