name: ci
on: push

jobs:
  spec:
    runs-on: ubuntu-latest
    name: spec ci
    steps:
      # this step makes your repo available to the next one
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - run: cd spec/setup/ && bash setup.sh && cd ../..
      - run: pip install soopervisor
      - run: cd spec/ && soopervisor build --clean-products-path

  basic-tutorial:
    runs-on: ubuntu-latest
    name: basic-tutorial ci
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - run: pip install soopervisor
      - run: cd basic-tutorial/ && soopervisor build --clean-products-path

  spec-r:
    runs-on: ubuntu-latest
    name: spec-r
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - run: pip install soopervisor
      - run: cd spec-r/ && soopervisor build --clean-products-path
  
  co2-emissions:
    runs-on: ubuntu-latest
    name: co2-emissions
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - run: pip install soopervisor
      - run: cd contrib/co2-emissions && soopervisor build --clean-products-path

  etl:
    runs-on: ubuntu-latest
    name: etl
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - run: pip install soopervisor
      - run: cd etl/ && soopervisor build --clean-products-path

  basic-ml:
    runs-on: ubuntu-latest
    name: basic-ml
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - run: |
        cd basic-ml
        pip install .
        pip install -r requirements.txt
        pytest
